### ISSUE TITLE
how to access files in dev server?

### ISSUE THREAD

**Issue by damianobarbati** [jvidalv/parcel-reporter-multiple-static-file-copier#1]
@jvidalv I'm trying your plugin but is it supposed to work in dev server mode?
Because files included like the following results in the index.html loaded instead:

```
// trying to load from assets folder, which is copied in dist with this plugin
const track = new Audio('/assets/match-music.mp3');
```

**Comment by jvidalv** [comment]
Hi @damianobarbati yes it work in boths envs, at least it worked when I was using it (Parcel 2). 

In any case, is the `match-music` being copied or not? Its not clear by your message. 

Normaly this plugin is used to copy files from `node_modules` to static paths like public, that then are available under `webpage.com/assets`.

**Comment by damianobarbati** [comment]
@jvidalv yes it's working! Thanks. 

Would you consider add support for a specific file (i.e: `.static-copier-rc`) here
https://github.com/jvidalv/parcel-reporter-multiple-static-file-copier/blob/master/index.js#L6 ?

**Comment by jvidalv** [comment]
Hi @damianobarbati,

Yes, sure, I'll do the pull this weekend. 

Its a shame that Parcel does not support extending the configuration of the plugin on `.parcelrc`.
