### ISSUE TITLE
TypeError: Cannot read property 'includes' of null

### ISSUE THREAD

**Issue by flyingduck92** [jvidalv/parcel-reporter-multiple-static-file-copier#2]
I already put `.parcelrc` and `multipleStaticFileCopier` based on the Readme but when running always give me "TypeError: Cannot read property 'includes' of null"

**Comment by jvidalv** [comment]
Hi, 

There is not an `Array.include` on this package, so the error must be somewhere else. 

Are you defining the prop as an array of objects, and are you sure that the files exists? 

```
{
  "multipleStaticFileCopier": [
    {
      "origin": "public",
      "destination": "dist/public/"
    }
  ]
}

```
